### ISSUE TITLE
Review Comments for cPP_MOD-template.adoc

### ISSUE THREAD

**Issue by ansukert** [itc-wgtools/cPP-Tools#34]
Brian,

I looked over the cPP_MOD template and my comments are basically the same as the ones for the cPP Template - so I wont repeat them here.

The one comment I would add for this template is that IMHO you should either provide a definition of what a 'Mod' is in this context in the template at the beginning of the template or point the user to the CC document that has the definition of what a Mod is. Just goes with the basic rule I mentioned in my cPP template comments - don't assume the user knows what a MOD is here.

I think that this goes to a basic topic that we should discuss at our Tools WG Meeting today - what should be the basic assumption on these templates about what the intended user's knowledge of CCC is?

**Comment by woodbe** [comment]
The MOD here is the PP-Module template which is slightly different than a cPP (it doesn't have and SARs and has to have language pointing to the Base-PP for that instead). Otherwise this isn't any different than the cPP template.

A description is probably better contained elsewhere though (something that lays out what all these templates are for).

**Comment by woodbe** [comment]
I'm going to close this as we have added the overview document that is to provide a "what is this" for each template.
